name: Deploy to VPS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mkdir -p /var/www/roni
            cd /var/www/roni
            if [ ! -d ".git" ]; then
              git clone https://github.com/raselrk5588-source/smritilife.git .
            fi
            git config --global --add safe.directory /var/www/roni
            git fetch origin
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            git clean -fd
            docker-compose up -d --build
